---
- name: "Enable ufw"
  community.general.ufw:
    direction: incoming
    policy: deny
    state: enabled

- name: "Whitelist apache2 in ufw"
  community.general.ufw:
    rule: allow
    port: "{{ firewall_svc }}"
