---
- name: "Include variables"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: "Include os relevant tasks"
  ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"

- name: "Ensure latest index.html is present"
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: "Ensure relevant services started and enabled on boot"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ apache_services }}"

- name: "Configure firewall to allow traffic"
  ansible.builtin.include_tasks: "configure-{{ ansible_os_family }}-firewall.yml"
