---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    expected_content: Managed by Ansible

  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true

    - name: check web server is running
      ansible.builtin.uri:
        url: http://localhost
        return_content: true
      register: url_output
      failed_when: "expected_content not in url_output.content"
